stages:
  - test
  - coverage
  - deploy

before_script:
    #- module purge
  - export LANG=C
  - ulimit -s unlimited
  - ulimit -v unlimited
    #- module load git
  - echo "HOST " $(hostname)
    #  - module list
    #  - source .ci-env-vars
  - ./autogen.sh

# For some reason sometimes not-writable files remain, which cause trouble the
# next time a runner tries to clean-up
after_script:
  - chmod u+w -R .

intel-double-precision-mpi-noomp-avx512-jobs:
  tags:
    - avx512
  script:
    - ./autogen.sh
    - srun -n 1 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/configure_elpa.sh "FC=mpiifort CC=mpiicc --enable-option-checking=fatal CFLAGS=\"-O3 -xCORE-AVX512\" FCFLAGS=\"-O3 -CORE-AVX512\" SCALAPACK_LDFLAGS=\"\$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP\" SCALAPACK_FCFLAGS=\"\$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP\" --enable-avx512"
    - srun -n 1 -c 8 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/build_elpa.sh
    - srun -n 1 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/run_elpa.sh 2 "TEST_FLAGS=\"150 50 16\""

  total_coverage:
  only:
    - /.*master.*/
  stage: coverage
  tags:
    - coverage
  script:
    - echo "Generating coverage report"
    - ./ci_coverage_summary
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  tags:
    - coverage
  script:
    - echo "Publishing pages"
  artifacts:
    paths:
      - public
  only:
    - master
