stages:
  - test
  - coverage
  - deploy



before_script:
  - export LANG=C
  - ulimit -s unlimited
  - ulimit -v unlimited
  - echo "HOST " $(hostname)
  - if [ "$(hostname)" = "buildtest-rzg" ]; then module purge && module load git && module list && source .ci-env-vars; fi
  - if [ "$(hostname)" = "amarek-elpa-gitlab-runner-1" ]; then module purge && module load git && module list && source .ci-env-vars; fi
  - if [ "$(hostname)" = "amarek-elpa-gitlab-runner-2" ]; then module purge && module load git && module list && source .ci-env-vars; fi
  - if [ "$(hostname)" = "amarek-elpa-gitlab-runner-3" ]; then module purge && module load git && module list && source .ci-env-vars; fi
  - if [ "$(hostname)" = "amarek-elpa-gitlab-runner-4" ]; then module purge && module load git && module list && source .ci-env-vars; fi
  - ./autogen.sh



# For some reason sometimes not-writable files remain, which cause trouble the
# next time a runner tries to clean-up
after_script:
  - chmod u+w -R .



# print coverage results
total_coverage:
  only:
    - /.*master.*/
  stage: coverage
  tags:
    - coverage
  script:
    - echo "Generating coverage report"
    - ./ci_coverage_summary
  artifacts:
    paths:
      - public



pages:
  stage: deploy
  tags:
    - coverage
  script:
    - echo "Publishing pages"
  artifacts:
    paths:
      - public
  only:
    - master



static-build:
  tags:
    - avx
  script:
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx" FCFLAGS="-O3 -axAVX" SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_NO_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_NO_MPI_NO_OMP" --with-mpi=no FC=ifort --enable-shared=no --enable-static=yes --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='150 50 16' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;



# test distcheck
distcheck:
  tags:
    - buildtest
  script:
    - ./configure --enable-option-checking=fatal --with-mpi=no --disable-sse-assembly --disable-sse --disable-avx --disable-avx2 || { cat config.log; exit 1; }
    # stupid 'make distcheck' leaves behind write-protected files that the stupid gitlab runner cannot remove
    - make distcheck DISTCHECK_CONFIGURE_FLAGS="--with-mpi=no --disable-sse-assembly --disable-sse --disable-avx --disable-avx2" TASKS=2 TEST_FLAGS="150 50 16" || { chmod u+rwX -R . ; exit 1 ; }



# test_project
test_project:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpif90 --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project/build
    - pushd test_project/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpif90 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd



# test_project_legacy_api
test_project_legacy_api:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpif90 --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_legacy_api/build
    - pushd test_project_legacy_api/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpif90 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd



# test_project_2stage
test_project_2stage:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpif90 --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_2stage/build
    - pushd test_project_2stage/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpif90 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real2
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd



# test_project_2stage_legacy_api
test_project_2stage_legacy_api:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpif90 --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_2stage_legacy_api/build
    - pushd test_project_2stage_legacy_api/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpif90 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real2
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd



# test_project_intel
test_project_intel:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpiifort --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project/build
    - pushd test_project/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpiifort || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd



# test_project_intel_legacy_api
test_project_intel_legacy_api:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpiifort --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_legacy_api/build
    - pushd test_project_legacy_api/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpiifort || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd



# test_project_2stage_intel
test_project_2stage_intel:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpiifort --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_2stage/build
    - pushd test_project_2stage/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpiifort || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real2
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd



# test_project_2stage_intel_legacy_api
test_project_2stage_intel_legacy_api:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpiifort --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_2stage_legacy_api/build
    - pushd test_project_2stage_legacy_api/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpiifort || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real2
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd



#The tests follow here
# gnu-gnu-mpi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage-avx2-no-address-sanitize
gnu-gnu-mpi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage_avx2-no-address-sanitize-jobs:
  tags:
    - avx2
  script:
    - srun -n 1 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/configure_elpa.sh " CC=\"mpicc\" CFLAGS=\"-O3 -mavx2 -mfma\" FC=\"mpif90\" FCFLAGS=\"-O3 -mavx2 -mfma\" SCALAPACK_LDFLAGS=\" $MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP \" SCALAPACK_FCFLAGS=\" $MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP \" --enable-option-checking=fatal --with-mpi=1 --disable-openmp --disable-single-precision --disable-assumed-size --disable-band-to-full-blocking --disable-gpu --enable-avx2"
    - srun -n 1 -c 8 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/build_elpa.sh
    - srun -n 2  --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/run_elpa.sh 2 " TEST_FLAGS=\"150 150 16\"  || { cat test-suite.log; exit 1; }"



# gnu-gnu-nompi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage-avx2-no-address-sanitize
gnu-gnu-nompi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage_avx2-no-address-sanitize-jobs:
  tags:
    - avx2
  script:
    - srun -n 1 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/configure_elpa.sh " CC=\"gcc\" CFLAGS=\"-O3 -mavx2 -mfma\" FC=\"gfortran\" FCFLAGS=\"-O3 -mavx2 -mfma\" SCALAPACK_LDFLAGS=\" $MKL_GFORTRAN_SCALAPACK_LDFLAGS_NO_MPI_NO_OMP \" SCALAPACK_FCFLAGS=\" $MKL_GFORTRAN_SCALAPACK_FCFLAGS_NO_MPI_NO_OMP \" --enable-option-checking=fatal --with-mpi=0 --disable-mpi-module --disable-openmp --disable-single-precision --disable-assumed-size --disable-band-to-full-blocking --disable-gpu --enable-avx2"
    - srun -n 1 -c 8 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/build_elpa.sh
    - srun -n 2  --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/run_elpa.sh 2 " TEST_FLAGS=\"150 150 16\"  || { cat test-suite.log; exit 1; }"



# gnu-intel-mpi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage-avx2-no-address-sanitize
gnu-intel-mpi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage_avx2-no-address-sanitize-jobs:
  tags:
    - avx2
  script:
    - srun -n 1 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/configure_elpa.sh " CC=\"mpicc\" CFLAGS=\"-O3 -mavx2 -mfma\" FC=\"mpiifort\" FCFLAGS=\"-O3 -march=core-avx2\" SCALAPACK_LDFLAGS=\" $MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP \" SCALAPACK_FCFLAGS=\" $MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP \" --enable-option-checking=fatal --with-mpi=1 --disable-openmp --disable-single-precision --disable-assumed-size --disable-band-to-full-blocking --disable-gpu --enable-avx2"
    - srun -n 1 -c 8 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/build_elpa.sh
    - srun -n 2  --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/run_elpa.sh 2 " TEST_FLAGS=\"150 150 16\"  || { cat test-suite.log; exit 1; }"



# gnu-intel-nompi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage-avx2-no-address-sanitize
gnu-intel-nompi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage_avx2-no-address-sanitize-jobs:
  tags:
    - avx2
  script:
    - srun -n 1 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/configure_elpa.sh " CC=\"gcc\" CFLAGS=\"-O3 -mavx2 -mfma\" FC=\"ifort\" FCFLAGS=\"-O3 -march=core-avx2\" SCALAPACK_LDFLAGS=\" $MKL_INTEL_SCALAPACK_LDFLAGS_NO_MPI_NO_OMP \" SCALAPACK_FCFLAGS=\" $MKL_INTEL_SCALAPACK_FCFLAGS_NO_MPI_NO_OMP \" --enable-option-checking=fatal --with-mpi=0 --disable-mpi-module --disable-openmp --disable-single-precision --disable-assumed-size --disable-band-to-full-blocking --disable-gpu --enable-avx2"
    - srun -n 1 -c 8 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/build_elpa.sh
    - srun -n 2  --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/run_elpa.sh 2 " TEST_FLAGS=\"150 150 16\"  || { cat test-suite.log; exit 1; }"



# intel-intel-mpi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage-avx2-no-address-sanitize
intel-intel-mpi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage_avx2-no-address-sanitize-jobs:
  tags:
    - avx2
  script:
    - srun -n 1 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/configure_elpa.sh " CC=\"mpiicc\" CFLAGS=\"-O3 -march=core-avx2\" FC=\"mpiifort\" FCFLAGS=\"-O3 -march=core-avx2\" SCALAPACK_LDFLAGS=\" $MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP \" SCALAPACK_FCFLAGS=\" $MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP \" --enable-option-checking=fatal --with-mpi=1 --disable-openmp --disable-single-precision --disable-assumed-size --disable-band-to-full-blocking --disable-gpu --enable-avx2"
    - srun -n 1 -c 8 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/build_elpa.sh
    - srun -n 2  --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/run_elpa.sh 2 " TEST_FLAGS=\"150 150 16\"  || { cat test-suite.log; exit 1; }"



# intel-intel-nompi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage-avx2-no-address-sanitize
intel-intel-nompi-noopenmp-double-precision-no-assumed-size-no-band-to-full-blocking-no-gpu-no-coverage_avx2-no-address-sanitize-jobs:
  tags:
    - avx2
  script:
    - srun -n 1 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/configure_elpa.sh " CC=\"icc\" CFLAGS=\"-O3 -march=core-avx2\" FC=\"ifort\" FCFLAGS=\"-O3 -march=core-avx2\" SCALAPACK_LDFLAGS=\" $MKL_INTEL_SCALAPACK_LDFLAGS_NO_MPI_NO_OMP \" SCALAPACK_FCFLAGS=\" $MKL_INTEL_SCALAPACK_FCFLAGS_NO_MPI_NO_OMP \" --enable-option-checking=fatal --with-mpi=0 --disable-mpi-module --disable-openmp --disable-single-precision --disable-assumed-size --disable-band-to-full-blocking --disable-gpu --enable-avx2"
    - srun -n 1 -c 8 --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/build_elpa.sh
    - srun -n 2  --partition=gp --nodelist=gp02 --time=40 /scratch/elpa/bin/run_elpa.sh 2 " TEST_FLAGS=\"150 150 16\"  || { cat test-suite.log; exit 1; }"



