stages:
  - test
  - coverage
  - deploy

before_script:
  - module purge
  - export LANG=C
  - ulimit -s unlimited
  - ulimit -v unlimited
  - module load git
  - echo "HOST " $HOST
  - module list
  - source .ci-env-vars


# For some reason sometimes not-writable files remain, which cause trouble the
# next time a runner tries to clean-up
after_script:
  - chmod u+w -R .


########################################################################################
#
# jobs for intel/gfortran double/single precision mpi and no openmp no cuda SSE/AVX
# - all runners on "cpu"
# - including coverage runs
#
########################################################################################
# intel double precision mpi noomp AVX/SSE
intel-double-precision-mpi-noomp-jobs:
  only:
    - /.*master.*/
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx" FCFLAGS="-O3 -axAVX" SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$SCALAPACK_FCFLAGS_MPI_NO_OMP" --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='150 50 16' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;

# intel double precision mpi noomp AVX/SSE large
intel-double-precision-mpi-noomp-large-jobs:
  only:
    - /.*master.*/
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx" FCFLAGS="-O3 -axAVX" SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP" --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='1500 500 16' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;

# intel single precision mpi noomp AVX/SSE
intel-single-precision-mpi-noomp-jobs:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx" FCFLAGS="-O3 -mavx" SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP" --enable-single-precision --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='150 50 16' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;

# gfortran double precision mpi noomp AVX/SSE
gfortran-double-precision-mpi-noomp-avx-jobs:
  only:
    - /.*master.*/
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx -fsanitize=address" FCFLAGS="-O3 -mavx -fsanitize=address" SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" --disable-avx2 FC=mpif90 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='150 50 16' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;

# gfortran single precision mpi noomp AVX/SSE
gfortran-single-precision-mpi-noomp-jobs:
  only:
    - /.*master.*/
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx" FCFLAGS="-O3 -mavx" SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" --disable-avx2 FC=mpif90 --enable-single-precision || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='150 50 16' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;

# gfortran single precision mpi noomp AVX/SSE no legacy
gfortran-single-precision-mpi-noomp-no-legacy-jobs:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx -fsanitize=address" FCFLAGS="-O3 -mavx -fsanitize=address" SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" --disable-avx2 FC=mpif90 --enable-single-precision --disable-legacy || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='150 50 16' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;

# gfortran single precision mpi noomp AVX/SSE qr
gfortran-single-precision-mpi-noomp-qr-jobs:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx -fsanitize=address" FCFLAGS="-O3 -mavx -fsanitize=address" SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" --disable-avx2 FC=mpif90 --enable-single-precision || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='1500 500 64' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;

# gfortran double precision mpi noomp AVX/SSE, no assumed size
gfortran-double-precision-mpi-noomp-no-assumed-size-jobs:
  only:
    - /.*master.*/
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx -fsanitize=address" FCFLAGS="-O3 -mavx -fsanitize=address" SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" --disable-avx2 FC=mpif90  --disable-assumed-size || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='150 50 16' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;

# gfortran single precision mpi noomp AVX/SSE, no assumed size
gfortran-single-precision-mpi-noomp-no-assumed-size-jobs:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx -fsanitize=address" FCFLAGS="-O3 -mavx -fsanitize=address" SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" --disable-avx2 FC=mpif90 --enable-single-precision --disable-assumed-size || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='150 50 16' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;



static-build:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal CFLAGS="-O3 -mavx" FCFLAGS="-O3 -axAVX" SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_NO_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_NO_MPI_NO_OMP" --with-mpi=no FC=ifort --enable-shared=no --enable-static=yes --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - make check TASKS=2 TEST_FLAGS='150 50 16' || { cat test-suite.log; exit 1; }
    - grep -i "Expected %stop" test-suite.log && exit 1 || true ;

# test distcheck
distcheck:
  tags:
    - buildtest
  script:
    - ./autogen.sh
    - ./configure --enable-option-checking=fatal --with-mpi=no --disable-sse-assembly --disable-sse --disable-avx --disable-avx2 || { cat config.log; exit 1; }
    # stupid 'make distcheck' leaves behind write-protected files that the stupid gitlab runner cannot remove
    - make distcheck DISTCHECK_CONFIGURE_FLAGS="--with-mpi=no --disable-sse-assembly --disable-sse --disable-avx --disable-avx2" TASKS=2 TEST_FLAGS='150 50 16' || { chmod u+rwX -R . ; exit 1 ; }

# test test_project
test_project:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpif90 --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project/build
    - pushd test_project/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpif90 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd

# test test_project_legacy_api
test_project_legacy_api:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpif90 --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_legacy_api/build
    - pushd test_project_legacy_api/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpif90 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd

# test test_project_2stage
test_project_2stage:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpif90 --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_2stage/build
    - pushd test_project_2stage/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpif90 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real2
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd


# test test_project_2stage_legacy_api
test_project_2stage_legacy_api:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpif90 --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_2stage_legacy_api/build
    - pushd test_project_2stage_legacy_api/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpif90 || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real2
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd

test_project_intel:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpiifort --prefix=$PWD/installdest --disable-sse-assembly --disable-sse --disable-avx --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project/build
    - pushd test_project/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpiifort || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest

test_project_intel_legacy_api:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpiifort --prefix=$PWD/installdest --disable-sse-assembly --disable-sse --disable-avx --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_legacy_api/build
    - pushd test_project_legacy_api/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpiifort || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest

test_project_2stage_intel:
 tags:
   - buildtest
 script:
   - mkdir build
   - pushd build
   - ../autogen.sh
   - ../configure --enable-option-checking=fatal SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpiifort --prefix=$PWD/installdest --disable-sse-assembly --disable-sse --disable-avx --disable-avx2 || { cat config.log; exit 1; }
   - make -j 8
   - make install
   - popd
   - mkdir test_project_2stage/build
   - pushd test_project_2stage/build
   - ../autogen.sh
   - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpiifort || { cat config.log; exit 1; }
   - make -j 8
   - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
   - ./test_real2
   - make distclean
   - popd
   - pushd build
   - make distclean
   - rm -rf installdest


test_project_2stage_intel_legacy_api:
 tags:
   - buildtest
 script:
   - mkdir build
   - pushd build
   - ../autogen.sh
   - ../configure --enable-option-checking=fatal SCALAPACK_LDFLAGS="$MKL_INTEL_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_INTEL_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpiifort --prefix=$PWD/installdest --disable-sse-assembly --disable-sse --disable-avx --disable-avx2 || { cat config.log; exit 1; }
   - make -j 8
   - make install
   - popd
   - mkdir test_project_2stage_legacy_api/build
   - pushd test_project_2stage_legacy_api/build
   - ../autogen.sh
   - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpiifort || { cat config.log; exit 1; }
   - make -j 8
   - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
   - ./test_real2
   - make distclean
   - popd
   - pushd build
   - make distclean
   - rm -rf installdest

# test test_project_C
test_project_C:
  tags:
    - buildtest
  script:
    - mkdir build
    - pushd build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal FCFLAGS="-march=native" CFLAGS="-march=native" --disable-avx2 SCALAPACK_LDFLAGS="$MKL_GFORTRAN_SCALAPACK_LDFLAGS_MPI_NO_OMP" SCALAPACK_FCFLAGS="$MKL_GFORTRAN_SCALAPACK_FCFLAGS_MPI_NO_OMP" FC=mpif90 --prefix=$PWD/installdest --disable-avx2 || { cat config.log; exit 1; }
    - make -j 8
    - make install
    - popd
    - mkdir test_project_C/build
    - pushd test_project_C/build
    - ../autogen.sh
    - ../configure --enable-option-checking=fatal PKG_CONFIG_PATH=../../build/installdest/lib/pkgconfig FC=mpif90 CC=mpicc || { cat config.log; exit 1; }
    - make -j 8
    - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
    - ./test_real
    - make distclean
    - popd
    - pushd build
    - make distclean
    - rm -rf installdest
    - popd

