before_script:
  - export LANG=C
  - module load impi/5.1.3 intel/16.0 gcc/4.9 mkl/11.3 autotools pkg-config 2>&1 | grep "ERROR" && exit 1 || true
  - module list
  - export LD_LIBRARY_PATH=$MKL_HOME/lib/intel64:$LD_LIBRARY_PATH
  - export PATH=/home/elpa/python-3.6/bin:$PATH
  - env

# define two stages, that way coverage only runs after all other
# tests have been done.
stages:
  - test
  - coverage

cpu-large-1-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 1/12
  artifacts:
    paths:
      - coverage_data

cpu-large-2-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 2/12
  artifacts:
    paths:
      - coverage_data

cpu-large-3-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 3/12
  artifacts:
    paths:
      - coverage_data

cpu-large-4-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 4/12
  artifacts:
    paths:
      - coverage_data

cpu-large-5-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 5/12
  artifacts:
    paths:
      - coverage_data

cpu-large-6-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 6/12
  artifacts:
    paths:
      - coverage_data

cpu-large-7-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 7/12
  artifacts:
    paths:
      - coverage_data

cpu-large-8-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 8/12
  artifacts:
    paths:
      - coverage_data

cpu-large-9-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 9/12
  artifacts:
    paths:
      - coverage_data

cpu-large-10-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 10/12
  artifacts:
    paths:
      - coverage_data

cpu-large-11-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 11/12
  artifacts:
    paths:
      - coverage_data

cpu-large-12-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 1500 50 16 -p 12/12
  artifacts:
    paths:
      - coverage_data

cpu-small-1-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 1/12
  artifacts:
    paths:
      - coverage_data

cpu-small-2-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 2/12
  artifacts:
    paths:
      - coverage_data

cpu-small-3-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 3/12
  artifacts:
    paths:
      - coverage_data

cpu-small-4-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 4/12
  artifacts:
    paths:
      - coverage_data

cpu-small-5-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 5/12
  artifacts:
    paths:
      - coverage_data

cpu-small-6-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 6/12
  artifacts:
    paths:
      - coverage_data

cpu-small-7-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 7/12
  artifacts:
    paths:
      - coverage_data

cpu-small-8-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 8/12
  artifacts:
    paths:
      - coverage_data

cpu-small-9-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 9/12
  artifacts:
    paths:
      - coverage_data

cpu-small-10-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 10/12
  artifacts:
    paths:
      - coverage_data

cpu-small-11-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 11/12
  artifacts:
    paths:
      - coverage_data

cpu-small-12-12:
  tags:
    - cpu
  script:
    - ./autogen.sh
    - ./gitlab_ci_test cpu 150 50 16 -p 12/12
  artifacts:
    paths:
      - coverage_data

emulated-small-1-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 1/12
  artifacts:
    paths:
      - coverage_data

emulated-small-2-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 2/12
  artifacts:
    paths:
      - coverage_data

emulated-small-3-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 3/12
  artifacts:
    paths:
      - coverage_data

emulated-small-4-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 4/12
  artifacts:
    paths:
      - coverage_data

emulated-small-5-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 5/12
  artifacts:
    paths:
      - coverage_data

emulated-small-6-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 6/12
  artifacts:
    paths:
      - coverage_data

emulated-small-7-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 7/12
  artifacts:
    paths:
      - coverage_data

emulated-small-8-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 8/12
  artifacts:
    paths:
      - coverage_data

emulated-small-9-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 9/12
  artifacts:
    paths:
      - coverage_data

emulated-small-10-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 10/12
  artifacts:
    paths:
      - coverage_data

emulated-small-11-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 11/12
  artifacts:
    paths:
      - coverage_data

emulated-small-12-12:
  tags:
    - emulated
  script:
    - ./autogen.sh
    - ./gitlab_ci_test emulated 50 50 32 -p 12/12
  artifacts:
    paths:
      - coverage_data

#gpu-large-jobs:
#  tags:
#    - gpu
#  script:
#    - ./autogen.sh
#    - ./gitlab_ci_test gpu 1500 500 128
# artifacts:
#   paths:
#     - coverage_data
#

total_coverage:
  stage: coverage
  tags:
    - cpu
  script:
    - ./ci_coverage_summary
  artifacts:
    paths:
      - coverage_data
